name: AwesomeItems
main: net.somethingsuperawesome.awesomeitems.AwesomeItems
version: 1.0
commands:
   awesomeitem:
      usage: /<command> <item>
      aliases: [ai,aweit]
   newawesomeitem:
      usage: /<command> <material>
      aliases: [newai, nai, newaweit]